# This file was generated by GoReleaser. DO NOT EDIT.
cask "reasonix" do
  version "1.38.3"

  on_macos do
    on_arm do
      sha256 "2077cc26cb4d3b2ebc1c980cdeb08d26072c291ee70b529c28085087fec537bd"
      url "https://github.com/esengine/DeepSeek-Reasonix/releases/download/v#{version}/reasonix-darwin-arm64.tar.gz"
    end
    on_intel do
      sha256 "22a48fcd817e6262d95964e9c294b956bea2d881e08ab9fea376600ed3e1654a"
      url "https://github.com/esengine/DeepSeek-Reasonix/releases/download/v#{version}/reasonix-darwin-amd64.tar.gz"
    end
  end
  on_linux do
    on_arm do
      sha256 "96e397ec4bf4d0072333fa40b7f30127f8ec1ddb04964d2569f21212409f03c8"
      url "https://github.com/esengine/DeepSeek-Reasonix/releases/download/v#{version}/reasonix-linux-arm64.tar.gz"
    end
    on_intel do
      sha256 "517ba19e315b8bcc31d5ebecafa6eb0aa56dd7455c20cd1aede0fa172b657d3c"
      url "https://github.com/esengine/DeepSeek-Reasonix/releases/download/v#{version}/reasonix-linux-amd64.tar.gz"
    end
  end

  name "reasonix"
  desc "Cache-first DeepSeek coding agent for the terminal."
  homepage "https://github.com/esengine/DeepSeek-Reasonix"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "reasonix"

  postflight do
    if OS.mac?
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/reasonix"]
    end
  end

  # No zap stanza required
end
