# This file was generated by GoReleaser. DO NOT EDIT.
cask "reasonix" do
  version "1.10.0"

  on_macos do
    on_intel do
      sha256 "80c14ba7974a645cd9c004c36d8af195afcd595390c117484c1f09ccc51ecd91"
      url "https://github.com/esengine/DeepSeek-Reasonix/releases/download/v#{version}/reasonix-darwin-amd64.tar.gz"
    end
    on_arm do
      sha256 "aca3269c295722ba295a19363ed7455cecad8808806af96470cb0a70d746ee12"
      url "https://github.com/esengine/DeepSeek-Reasonix/releases/download/v#{version}/reasonix-darwin-arm64.tar.gz"
    end
  end

  on_linux do
    on_intel do
      sha256 "239105936f787d3f0b43855815434c49be7f4380be30c611ae1510e010dbffba"
      url "https://github.com/esengine/DeepSeek-Reasonix/releases/download/v#{version}/reasonix-linux-amd64.tar.gz"
    end
    on_arm do
      sha256 "e496cf98fc26362cc90c58cbb037875147c0f34f1aa9c63b17ac2a3ce7dd4a80"
      url "https://github.com/esengine/DeepSeek-Reasonix/releases/download/v#{version}/reasonix-linux-arm64.tar.gz"
    end
  end

  name "reasonix"
  desc "Cache-first DeepSeek coding agent for the terminal."
  homepage "https://github.com/esengine/DeepSeek-Reasonix"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "reasonix"

  postflight do
    if OS.mac?
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/reasonix"]
    end
  end

  # No zap stanza required

end
