# This file was generated by GoReleaser. DO NOT EDIT.
cask "reasonix" do
  version "1.21.4"

  on_macos do
    on_intel do
      sha256 "dda6cce26cd4a8bd098c698b71fa428b76f1e2b33cf5d9cd061e4d86011634fb"
      url "https://github.com/esengine/DeepSeek-Reasonix/releases/download/v#{version}/reasonix-darwin-amd64.tar.gz"
    end
    on_arm do
      sha256 "869c44fe96d3ba321401b73808b16bd85ac8fa4a20eb38bbd9dce39e9c8ecf74"
      url "https://github.com/esengine/DeepSeek-Reasonix/releases/download/v#{version}/reasonix-darwin-arm64.tar.gz"
    end
  end

  on_linux do
    on_intel do
      sha256 "310e80bc7b1dcd0eff8c428b3dac4a27240f5ea2bd6455c28f7479be8f16eda0"
      url "https://github.com/esengine/DeepSeek-Reasonix/releases/download/v#{version}/reasonix-linux-amd64.tar.gz"
    end
    on_arm do
      sha256 "fc7d929c5ffdc3fc57c677ba67cfccf27859bd8a1da3371ddfc4a2a49da27658"
      url "https://github.com/esengine/DeepSeek-Reasonix/releases/download/v#{version}/reasonix-linux-arm64.tar.gz"
    end
  end

  name "reasonix"
  desc "Cache-first DeepSeek coding agent for the terminal."
  homepage "https://github.com/esengine/DeepSeek-Reasonix"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "reasonix"

  postflight do
    if OS.mac?
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/reasonix"]
    end
  end

  # No zap stanza required

end
